name: Docker Series Builds

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }} 
          repository: Dinahalem/APP_Workflow
          
          
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
          context: .
          push: true
          tags: dina2022/website:latest
      
 
  
  deploy:
    name: Push to EC2 Instance
    runs-on: self-hosted

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      
      - name: Deploy to Server1
        #uses: Dinahalem/APP_Workflow@main
        env: 
           SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
           SOURCE: /
           REMOTE_HOST: ${{secrets.SSH_HOST}}
           REMOTE_USER:  ${{secrets.SSH_USER}}
           TARGET:  ${{secrets.TARGET_DIR}}
        run: |
           docker stop new_app
           docker rm new_app
           docker run -d -p 80:80 --name new_app dina2022/website  
           
      - name: Deploy to k8s
        run: |
           kubectl apply -f deploy/project-deployment.yaml
           kubectl apply -f deploy/project-node-port.yaml

