name: Push-to-EC2

on: push

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: self-hosted

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      
      - name: Deploy to Server1
        #uses: Dinahalem/APP_Workflow@main
        env: 
           SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
           SOURCE: /
           REMOTE_HOST: ${{secrets.SSH_HOST}}
           REMOTE_USER:  ${{secrets.SSH_USER}}
           TARGET:  ${{secrets.TARGET_DIR}}
        run: |
           docker run -d -p 9090:80 --name new_app dina2022/website
           
           CNAME=$CONTAINER_NAME-$CODE_VERSION
           if [ "$(docker ps -qa -f name=$CNAME)" ]; then
           echo ":: Found container - $CNAME"
             if [ "$(docker ps -q -f name=$CNAME)" ]; then
              echo ":: Stopping running container - $CNAME"
              docker stop $CNAME;
            fi
            echo ":: Removing stopped container - $CNAME"
            docker rm $CNAME;
           fi
           
